/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.fabric;

import io.fabric.sdk.android.Fabric;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.kroll.common.Log;

import com.crashlytics.android.Crashlytics;

@Kroll.module(name="Fabric", id="ti.fabric")
public class FabricModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "FabricModule";

	public FabricModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	@Kroll.method
	public void init()
	{
		Fabric.with(TiApplication.getInstance(), new Crashlytics());
	}
	
	@Kroll.method @Kroll.getProperty
	public String getVersion()
	{
		return Crashlytics.getInstance().core.getVersion();
	}
	
	@Kroll.method
	public void crash()
	{
		Crashlytics.getInstance().core.crash();
	}
	
	@Kroll.method
	public void logException(Object error)
	{
		if(error instanceof Throwable){
			Crashlytics.getInstance().core.logException((Throwable) error);	
		}
	}
	
	@Kroll.method
	public void leaveBreadcrumb(String value)
	{
		Crashlytics.getInstance().core.log(value);
	}
	
	@Kroll.method
	public void setUserIdentifier(String value)
	{
		Crashlytics.getInstance().core.setUserIdentifier(value);
	}
	
	@Kroll.method
	public void setUserName(String value)
	{
		Crashlytics.getInstance().core.setUserName(value);
	}
	
	@Kroll.method
	public void setUserEmail(String value)
	{
		Crashlytics.getInstance().core.setUserEmail(value);
	}
	
	@Kroll.method
	public void setInt(String key, Object value)
	{
		Crashlytics.getInstance().core.setInt(key, TiConvert.toInt(value));
	}
	
	@Kroll.method
	public void setFloat(String key, Object value)
	{
		Crashlytics.getInstance().core.setFloat(key, TiConvert.toFloat(value));
	}
	
	@Kroll.method
	public void setDouble(String key, Object value)
	{
		Crashlytics.getInstance().core.setDouble(key, TiConvert.toDouble(value));
	}
	
	@Kroll.method
	public void setBool(String key, Object value)
	{
		Crashlytics.getInstance().core.setBool(key, TiConvert.toBoolean(value));
	}
	
	@Kroll.method
	public void setString(String key, Object value)
	{
		Crashlytics.getInstance().core.setString(key, TiConvert.toString(value));
	}
}

